version: "2"
services:
  archive-parser:
    image: grafana/devtools-github-archive-parser:latest
    network_mode: host
    command:
      - '-database=mysql'
      - '-connstring=test:test@tcp(localhost:3306)/github_stats'
      - '-maxDuration=10h'
      - '-orgNames=grafana'
      - '-overrideAllFiles=true'
      - '-verbose=true'