version: "2"
services:
  event-aggregator:
    image: grafana/devtools-github-event-aggregator:latest
    network_mode: host
    command:
      - '-database=mysql'
      - '-fromConnectionstring=test:test@tcp(localhost:3306)/github_stats'
      - '-toConnectionstring=test:test@tcp(localhost:3306)/github_stats'
      - '-limit=5000'
      - '-verbose=true'