version: "2"
services:
  archive-parser:
    image: grafana/devtools-github-archive-parser:latest
    network_mode: host
    command:
      - '-database=postgres'
      - '-connstring=postgresql://test:test@localhost:5432/github_stats?sslmode=disable'
      - '-maxDuration=10h'
      - '-orgNames=grafana'
      - '-overrideAllFiles=true'
      - '-verbose=true'